name: Destroy PR Storybook

# only trigger on pull request closed events
on:
  pull_request:
    types: [closed]

jobs:
  destroy-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      
      - name: check pr dir existence
        id: check_dir
        run: |
          if [ -d "${PR_DIR}" ]
          then
            echo "::set-output name=pr_dir_exists::true"
          else
            echo "::set-output name=pr_dir_exists::false"
          fi
        env:
          PR_DIR: pr-${{ github.event.number }}

      - name: remove pr directory
        if: steps.check_dir.outputs.pr_dir_exists == 'true'
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git rm -r --cached ./pr-${PR}
          git status
          git add .
          git status
          git commit -m "chore: remove PR #${PR} storybook instance"
          git push origin gh-pages
        env:
          PR: ${{ github.event.number }}
